title: "d415k's CTF memos."
description: "CTFのWriteUpやCheatSheetをまとめていく。"
show_downloads: false
google_analytics: G-B9M57QVXJ3
theme: jekyll-theme-hacker

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      author: "d415k"
